### ISSUE TITLE
Checkboxes missed validation css classes

### ISSUE THREAD

**Issue by EugeneSnihovsky** [lookfirst/mui-rff#264]
**Checkboxes** missed css classes like `Mui-error Mui-required` when form validated and all fields marked with error.

I already read [#158](https://github.com/lookfirst/mui-rff/issues/158). And can't find solution to mark checkbox field as invalid manually.

It looks like a bug, because text fields has this classes and marks with read color on error by default

P.S: thanks for great repo. **final-form-material-ui** is dead and I thought I would have to rewrite everything, but your library saved me :)

**Comment by lookfirst** [comment]
Can you please provide a codesandbox that reproduces the error you're having? You can fork one of the example ones mentioned on the readme.

**Comment by EugeneSnihovsky** [comment]
Sorry for long response.
I recheck examples and figure out that
```tsx
<Checkboxes
  name='manualTrades'
   data={[ { label: translate('EDIT_ACCOUNT.CLOUD_ACCOUNT.CHECKBOX.PLACE_MANUAL_TRADES'), value: true } ]}
  required />
```
will render checkbox and label in one line (this is what I need), but label will not have validation classes.

And if I use
```tsx
<Checkboxes
  name='manualTrades'
  data={[ { label: null, value: true } ]}
  label={ translate('EDIT_ACCOUNT.CLOUD_ACCOUNT.CHECKBOX.PLACE_MANUAL_TRADES') }
  required />
```
label will have validation classes but checkbox and label will rendered in different lines. And I fix this with css
```scss
.ps-checkboxes {
  .MuiFormControl-root {
    position: relative;
    display: flex;
    flex-direction: row-reverse;

    & > .MuiFormGroup-root {
      width: 31px;
      display: flex;
      flex-direction: row;
      align-items: center;

      .MuiFormControlLabel-root {
        margin-right: 0;
      }
    }

    & > .MuiFormLabel-root {
      width: calc(100% - 31px);
      display: inline-flex;
      flex-direction: row;
      align-items: center;
      font-size: 20px;

      .MuiFormLabel-asterisk {
        display: none;
      }
    }

    & > .MuiFormHelperText-root {
      position: absolute;
      top: 100%;
      left: 0;
      width: 100%;
      margin-top: 0;
    }
  }
}
```
```tsx
<Grid
  className='ps-checkboxes'
  item
  xs={12}>
    <Checkboxes
      name='manualTrades'
      data={[ { label: null, value: true } ]}
      label={ translate('EDIT_ACCOUNT.CLOUD_ACCOUNT.CHECKBOX.PLACE_MANUAL_TRADES') }
      required />
</Grid>
```
This is dirty hack but it works :) So, probably issue can be closed. If I missed something and there are standard
way to place checkbox and label in one line and have validation classes for label - please let me know.
